name: Release WASM Plugin

on:
  push:
    tags:
      - "v*"

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Git
        run: git fetch --tags
      - name: Check Cargo.toml version matches tag
        run: .github/scripts/check-version.sh

  build-and-release:
    runs-on: ubuntu-latest
    needs: check-version
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-wasip1

      - name: Build WASM
        run: cargo build --release --target wasm32-wasip1

      - name: Extract crate name and version
        id: crateinfo
        run: |
          CRATE_NAME=$(grep '^name' Cargo.toml | head -n1 | sed -E 's/name = "(.*)"/\1/')
          VERSION=$(grep '^version' Cargo.toml | head -n1 | sed -E 's/version = "(.*)"/\1/')
          echo "crate_name=$CRATE_NAME" >> $GITHUB_OUTPUT
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Prepare release artifacts
        run: |
          mkdir release
          cp target/wasm32-wasip1/release/*.wasm release/plugin.wasm
          cp .traefik.yml release/

      - name: Create zip archive
        id: zip
        run: |
          cd release
          ZIP="${{ steps.crateinfo.outputs.crate_name }}-v${{ steps.crateinfo.outputs.version }}.zip"
          zip ../"$ZIP" plugin.wasm .traefik.yml
          echo "name=$ZIP" >> $GITHUB_OUTPUT

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ steps.zip.outputs.name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
