name: Release WASM Plugin

on:
  push:
    tags:
      - "v*"

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Git
        run: git fetch --tags
      - name: Check Cargo.toml version matches tag
        run: .github/scripts/check-version.sh

  build:
    needs: check-version
    uses: ./.github/workflows/build.yml

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download build assets
        uses: actions/download-artifact@v4
        with:
          name: build-assets
      - name: Check asset
        id: check
        run: |
          ASSET="${{ needs.build.outputs.name }}"
          if [[ ! "$ASSET" =~ \.zip$ ]]; then
            echo "Asset is not a zip file."
            exit 1
          fi
          unzip -l "$ASSET" | grep -q '\.traefik\.yml' || { echo ".traefik.yml not found in asset."; exit 1; }
          unzip -l "$ASSET" | grep -q 'plugin\.wasm' || { echo "plugin.wasm not found in asset."; exit 1; }
          echo "zip=$ASSET" >> $GITHUB_OUTPUT

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ steps.check.outputs.zip }}
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_MAINTENANCE_RESPONSE }}
