name: Release WASM Plugin

on:
  push:
    tags:
      - "v*"

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Git
        run: git fetch --tags
      - name: Check Cargo.toml version matches tag
        run: .github/scripts/check-version.sh

  build:
    needs: check-version
    uses: ./.github/workflows/build.yml

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download build assets
        uses: actions/download-artifact@v4
        with:
          name: build-assets

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ needs.build.outputs.name }}
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_MAINTENANCE_RESPONSE }}
