name: Test Plugin

on:
  - push
  - pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-wasip1
      - uses: Swatinem/rust-cache@v2
      - name: Clippy
        run: cargo clippy --all

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-wasip1
      - name: Rustfmt
        run: cargo fmt --all -- --check

  build:
    uses: ./.github/workflows/build.yml
    with:
      debug_build: true
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Download build assets
        uses: actions/download-artifact@v4
        with:
          name: build-assets
      - run: |
          mkdir -p .github/traefik/plugins/src/github.com/jannschu/maintenance-response/
          unzip -d .github/traefik/plugins/src/github.com/jannschu/maintenance-response/ "${{ needs.build.outputs.name }}"

      - name: Start Traefik
        run: |
          cd .github/traefik/
          docker compose up -d
          for i in {1..10}; do
            if curl -sf http://localhost/; then
              break
            fi
            sleep 1
          done

      - name: Save Traefik logs
        if: always()
        run: |
          docker logs $(docker ps -q --filter "name=^traefik-traefik") > traefik.log || true
          cat traefik.log
      - name: Upload Traefik logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: traefik-logs
          path: traefik.log
